---
- name: Upload web page
  hosts: STAGING_SERVERS_WEB
  become: yes
  
  vars:
    source    : ./mywebsite 
    destination : /var/www/html
    
  tasks:
  
  - block: #RH
         
      - name: Start webServer service RedHat
        service: name=httpd state=started enabled=yes
    
    when: ansible_os_family == "RedHat"
    
    
  - block: #Deb
         
      - name: Start webServer service Debian
        service: name=httpd state=started enabled=yes
    
    when: ansible_os_family == "Debian"  
    
  
  - name: Copy site to server`s directory
    copy: src={{ source }}/{{ item }} dest={{ destination }} mode=0555
    with_fileglob: "{{ source }}/*.*" 
    notify: 
        - restart Apache Deb
        - restart Apache RH
   
    handlers:
  - name: restart Apache RH
    service: name=httpd state=restarted
    when: ansible_os_family == "RedHat"
       
  - name: restart Apache Deb
    service: name=apache2 state=restarted  
    when: ansible_os_family == "Debian" 
