
---
- name: Install default apache Web Server
  hosts: PROD_SERVERS_WEB STAGING_SERVERS_WEB
  become: yes

  tasks:
  - name: Install apache web server
    yum: name=httpd state=latest

  - name: Start web server
    service: name=httpd state=started enabled=yes 
