
---
- name: Install default apache Web Server
  hosts: PROD_SERVERS_WEB STAGING_SERVERS_WEB
  become: yes

  tasks:
  
  - block: #RH
  
     - name: Install apache web server RH
       yum: name=httpd state=latest
    
    when: ansible_os_family == "RedHat"
  
  - block:   # Deb
  
      - name: Install apache web server Deb
        apt: name=apache2 state=latest
  
    when: ansible_os_family == "Debian" 
  
