
---
- name: Install packages
  hosts: all
  become: yes

  tasks:
    
  - block:   # for Ubuntu
      
      
      - name: partition set first part for www
        parted:
           device: /dev/vdb
           number: 1
           flags: [ lvm ]
           state: present
           part_end: 2048MiB
      
      - name: /dev/vdb info 
        parted:
          device: /dev/vdb
          unit: MiB
        register: device_info  
      
      - name: partition set second part for mysql
        parted:
           device: /dev/vdb
           number: 2
           flags: [ lvm ]
           state: present
           part_end: "100%"
           part_start: "{{ device_info.partitions[0].end + 1}}MiB"
      
      - name: set filesystem 1
        filesystem:
          fstype: ext4
          dev: /dev/vdb1
        
      - name: set filesystem 2
        filesystem:
          fstype: xfs
          dev: /dev/vdb2
        
      - name: mount 1
        mount:
          fstype: ext4
          src: /dev/vdb1
          path: /var/www
          state: mounted
        
      - name: mount 2
        mount:
          fstype: xfs
          src: /dev/vdb2
          path: /var/lib/mysql
          state: mounted
   
    when: ansible_os_family == "Debian" 
  
