---
# tasks file for deploy_site
- block: #RH
         
     - name: Start webServer service RedHat
       service: name=httpd state=started enabled=yes
    
  when: ansible_os_family == "RedHat"
    
    
- block: #Deb
         
     - name: Start webServer service Debian
       service: name=httpd state=started enabled=yes
    
  when: ansible_os_family == "Debian"  
    
- name: Copy site to server`s directory
  copy: src={{ item }} dest={{ destination }} mode=0555
  with_fileglob: "{{ source }}/*.*" 
  notify: 
       - restart Apache Deb
       - restart Apache RH
